from __future__ import annotations

import html
import json
from pathlib import Path
from typing import TypedDict

from .analytics import Summary, summarize


class ScenarioSummary(TypedDict):
    name: str
    metrics: Summary


def compare_scenarios(scenarios: dict[str, str | Path]) -> list[ScenarioSummary]:
    if len(scenarios) < 2:
        raise ValueError("at least two scenarios are required")
    return [{"name": name, "metrics": summarize(path)} for name, path in sorted(scenarios.items())]


def write_comparison_json(rows: list[ScenarioSummary], output_path: str | Path) -> None:
    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = {"schema_version": "1.0", "scenarios": rows}
    target.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _bar_chart(
    rows: list[ScenarioSummary],
    metric: str,
    title: str,
    percentage: bool = False,
) -> str:
    width = 720
    bar_height = 34
    label_width = 150
    chart_width = 500
    values = [float(row["metrics"][metric]) for row in rows]  # type: ignore[literal-required]
    maximum = max(values) or 1.0
    items: list[str] = []
    for index, (row, value) in enumerate(zip(rows, values, strict=True)):
        y = 40 + index * (bar_height + 12)
        bar_width = value / maximum * chart_width
        display = f"{value:.3%}" if percentage else f"{value:.3f}"
        items.append(
            f'<text x="0" y="{y + 22}" class="label">{html.escape(row["name"])}</text>'
            f'<rect x="{label_width}" y="{y}" width="{bar_width:.1f}" height="{bar_height}" rx="5"/>'
            f'<text x="{label_width + bar_width + 8:.1f}" y="{y + 22}" class="value">{display}</text>'
        )
    height = 60 + len(rows) * (bar_height + 12)
    return (
        f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="{html.escape(title)}">'
        f'<text x="0" y="22" class="chart-title">{html.escape(title)}</text>'
        + "".join(items)
        + "</svg>"
    )


def render_html(rows: list[ScenarioSummary], output_path: str | Path) -> None:
    table_rows = "".join(
        "<tr>"
        f"<td>{html.escape(row['name'])}</td>"
        f"<td>{row['metrics']['runs']}</td>"
        f"<td>{row['metrics']['mean_availability']:.3%}</td>"
        f"<td>{row['metrics']['median_availability']:.3%}</td>"
        f"<td>{row['metrics']['availability_stddev']:.5f}</td>"
        f"<td>{row['metrics']['p95_downtime_hours']:.3f}</td>"
        "</tr>"
        for row in rows
    )
    availability_chart = _bar_chart(rows, "mean_availability", "Mean availability", True)
    downtime_chart = _bar_chart(rows, "p95_downtime_hours", "P95 downtime hours")
    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Reliability Scenario Comparison</title>
<style>
body{{font-family:Inter,system-ui,sans-serif;max-width:1000px;margin:40px auto;padding:0 20px;color:#172033}}
h1{{margin-bottom:8px}} .subtitle{{color:#5b6578;margin-bottom:28px}}
table{{border-collapse:collapse;width:100%;margin-bottom:32px}} th,td{{padding:10px;border-bottom:1px solid #dfe3ea;text-align:right}}
th:first-child,td:first-child{{text-align:left}} svg{{width:100%;margin:18px 0;background:#f8fafc;padding:16px;border-radius:10px}}
rect{{fill:#2563eb}} .label,.value{{font-size:14px;fill:#172033}} .chart-title{{font-size:17px;font-weight:700;fill:#172033}}
</style>
</head>
<body>
<h1>Reliability Scenario Comparison</h1>
<p class="subtitle">Versioned, reproducible analysis generated by reliability-lab.</p>
<table>
<thead><tr><th>Scenario</th><th>Runs</th><th>Mean availability</th><th>Median</th><th>Stddev</th><th>P95 downtime (h)</th></tr></thead>
<tbody>{table_rows}</tbody>
</table>
{availability_chart}
{downtime_chart}
</body>
</html>
"""
    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(document, encoding="utf-8")
